### ISSUE TITLE
[Level 42] - New Client Request

### ISSUE THREAD

**Issue by rich-guess** [rich-guess/amdemo#5]
- [x] What is the name of the client? 
Level 42

- [x] Do you have a company logo?

- [x] Do they have custom data?

1. - [x] BETA FTP Site Established
1. - [x] Base spice created
1. - [x] Client settings established

**Expected Files**
1. - [x] Catalog Master
1. - [x] Catalog Mapping
1. - [x] Product 
1. - [x] Pricing
1. - [x] Product Features
1. - [x] Customer Account Information
1. - [x] Customer (Sold to Accounts)
1. - [x] Locations (Ship-To)
1. - [x] Rep Master
1. - [x] Rep to Account Mapping
1. - [x] User import (optional)
1. - [x] Inventory
1. - [x] Order History

**Supplemental Files**
1. - [x] Related Products
1. - [x] Technology
1. - [x] Technology Mapping

When files have been delivered, check them off. Development will pick them up when all files are available.

**Comment by rich-guess** [comment]
FTP: user/pass
